# Generated by Django 3.2 on 2021-11-18 09:27

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontext',
            name='text',
            field=djrichtextfield.models.RichTextField(verbose_name='Текст'),
        ),
    ]
