# Generated by Django 3.2 on 2021-12-01 14:27

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211124_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=djrichtextfield.models.RichTextField(null=True, verbose_name='Описание'),
        ),
    ]
